### ISSUE TITLE
🚧Initial project creation, config, and structure

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/kd-cli#2]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Create the project structure and config by doing the following: 

> **Note**
> Use other deno projects in the organization as a guide.

1. Create deno.json file
2. Create deno.config file
3. Setup VSCode launch.json
4. Setup tasks.json
    - Setup task for linting
    - Setup task for build (deno check)
5. Setup deno check system
6. Setup renovate.json
7. Create license file
8. Setup build status check workflow
9. Setup lint status check workflow
10. Other things not in this list that are discovered during development

### Acceptance Criteria

```[tasklist]
### CICD
- [x] The deno.json file has been created
- [x] The VSCode launch.json file has been setup
- [x] The tasks.json file has been setup
- [x] The renovate.json file has been setup
- [x] License file has been created
```

```[tasklist]
### Other
- [x] Setup build status check workflow
- [x] Setup lint status check workflow
- [x] The deno check system has been setup
- [x] sync bot workflow has been created
- [x] sysn status check workflow created
- [x] sync pr to issue sync workflow created
- [x] cicd script created to compile executable to all 4 targets
- [x] create release workflow
- [x] create test status check workflow
```

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
